package router

import (
	"golang-starter/src/handlers/http"

	_ "golang-starter/docs"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/cors"
	httpswagger "github.com/swaggo/http-swagger"
)

type HttpRouterImpl struct {
	handlers *http.HttpHandlerImpl
}

func NewHttpRoute(
	handlers *http.HttpHandlerImpl,
) *HttpRouterImpl {
	return &HttpRouterImpl{
		handlers: handlers,
	}
}

// setup cors
func (h *HttpRouterImpl) cors(r *chi.Mux) {
	r.Use(cors.AllowAll().Handler)
}

func (h *HttpRouterImpl) Router(r *chi.Mux) {
	h.cors(r)
	h.handlers.Router(r)

	// Setup swagger docs from autogenerated swagger
	r.Mount("/swagger", httpswagger.WrapHandler)
}
