// Code generated by "repogen"; DO NOT EDIT.
package entities

import (
	"github.com/guregu/null"
)

type ProductsImages struct {
	ProductimagesId int32    `db:"productimages_id"`
	ProductFkid     null.Int `db:"product_fkid"`
	Images          string   `db:"images"`
	CreatedAt       int64    `db:"created_at"`
	UpdatedAt       int64    `db:"updated_at"`
}

type ProductsImagesList []*ProductsImages
